export const STOCK_ICON_FILES: Record<string, "svg" | "png"> = {
  "aapl": "svg",
  "abnb": "svg",
  "adbe": "svg",
  "amd": "svg",
  "amzn": "svg",
  "bac": "svg",
  "csco": "svg",
  "googl": "svg",
  "ibm": "svg",
  "intc": "svg",
  "ko": "svg",
  "ma": "svg",
  "meta": "svg",
  "msft": "svg",
  "nflx": "svg",
  "nvda": "svg",
  "orcl": "svg",
  "pypl": "svg",
  "tsla": "svg",
  "v": "svg",
} as const;
